id = "deck_star-wars-episode-ix-the-rise-of-skywalker_2c7e5317"
revision = 4
name = "Star Wars Episode IX: The Rise of Skywalker"
category = "Star Wars"
audience = "Family"
difficulty = "Medium"
special_prompt_note = "Cards should include people, places, droids, creatures, ships, objects, events, and memorable details introduced in Episode IX: The Rise of Skywalker."
photo_file_name = "star-wars-episode-ix-the-rise-of-skywalker-2c7e5317-cover.jpg"
spoiler_mode = true
spoiler_series = "star_wars"

[[cards]]
text = "Babu Frik"
first_revealed_installment = 11

[[cards]]
text = "Zorii Bliss"
first_revealed_installment = 11

[[cards]]
text = "D-O"
first_revealed_installment = 11

[[cards]]
text = "Jannah"
first_revealed_installment = 11

[[cards]]
text = "Klaud"
first_revealed_installment = 11

[[cards]]
text = "General Pryde"
first_revealed_installment = 11

[[cards]]
text = "Boolio"
first_revealed_installment = 11

[[cards]]
text = "Exegol"
first_revealed_installment = 11

[[cards]]
text = "Kijimi"
first_revealed_installment = 11

[[cards]]
text = "Pasaana"
first_revealed_installment = 11

[[cards]]
text = "Kef Bir"
first_revealed_installment = 11

[[cards]]
text = "Ajan Kloss"
first_revealed_installment = 11

[[cards]]
text = "Sith Wayfinder"
first_revealed_installment = 11

[[cards]]
text = "Sith Dagger"
first_revealed_installment = 11

[[cards]]
text = "Leia's Lightsaber"
first_revealed_installment = 11

[[cards]]
text = "Rey's Yellow Lightsaber"
first_revealed_installment = 11

[[cards]]
text = "Kylo Ren's Repaired Helmet"
first_revealed_installment = 11

[[cards]]
text = "Force Dyad"
first_revealed_installment = 11

[[cards]]
text = "Force Healing"
first_revealed_installment = 12

[[cards]]
text = "All the Jedi"
first_revealed_installment = 11

[[cards]]
text = "All the Sith"
first_revealed_installment = 11

[[cards]]
text = "Citizen's Fleet"
first_revealed_installment = 11

[[cards]]
text = "Battle of Exegol"
first_revealed_installment = 11

[[cards]]
text = "Sith Eternal"
first_revealed_installment = 11

[[cards]]
text = "Sith Trooper"
first_revealed_installment = 11

[[cards]]
text = "Dark Rey"
first_revealed_installment = 11

[[cards]]
text = "Rey Skywalker"
first_revealed_installment = 11

[[cards]]
text = "Ochi of Bestoon"
first_revealed_installment = 11

[[cards]]
text = "Bestoon Legacy"
first_revealed_installment = 11

[[cards]]
text = "TIE Whisper"
first_revealed_installment = 11

[[cards]]
text = "TIE Dagger"
first_revealed_installment = 11

[[cards]]
text = "Night Buzzard"
first_revealed_installment = 11

[[cards]]
text = "The Steadfast"
first_revealed_installment = 11

[[cards]]
text = "Sith Throne"
first_revealed_installment = 11

[[cards]]
text = "Festival of the Ancestors"
first_revealed_installment = 11

[[cards]]
text = "Orbak"
first_revealed_installment = 11

[[cards]]
text = "Vexis"
first_revealed_installment = 11

[[cards]]
text = "Aki-Aki"
first_revealed_installment = 11

[[cards]]
text = "Red-Eyed C-3PO"
first_revealed_installment = 11

[[cards]]
text = "Babu Frik's Workshop"
first_revealed_installment = 11

[[cards]]
text = "Spice Runners of Kijimi"
first_revealed_installment = 11

[[cards]]
text = "Death Star II Wreckage"
first_revealed_installment = 11

[[cards]]
text = "Company 77"
first_revealed_installment = 11

[[cards]]
text = "The Final Order"
first_revealed_installment = 11

[[cards]]
text = "Sith Citadel"
first_revealed_installment = 11

[[cards]]
text = "Wedge Antilles"
first_revealed_installment = 1

[[cards]]
text = "Lando Calrissian"
first_revealed_installment = 2

[[cards]]
text = "Emperor Palpatine"
first_revealed_installment = 2

[[cards]]
text = "Sith Runes"
first_revealed_installment = 13

[[cards]]
text = "Ben Solo"
first_revealed_installment = 7

[[cards]]
text = "Treadspeeder"
first_revealed_installment = 11

[[cards]]
text = "Beaumont Kin"
first_revealed_installment = 11

[[cards]]
text = "Kylo Ren"
first_revealed_installment = 7

[[cards]]
text = "Rey"
first_revealed_installment = 7

[[cards]]
text = "Finn"
first_revealed_installment = 7

[[cards]]
text = "Poe Dameron"
first_revealed_installment = 7

[[cards]]
text = "Maz Kanata"
first_revealed_installment = 7

[[cards]]
text = "General Hux"
first_revealed_installment = 7

[[cards]]
text = "Rose Tico"
first_revealed_installment = 9

[[cards]]
text = "Luke Skywalker"
first_revealed_installment = 1

[[cards]]
text = "Leia Organa"
first_revealed_installment = 1

[[cards]]
text = "Chewbacca"
first_revealed_installment = 1

[[cards]]
text = "C-3PO"
first_revealed_installment = 1

[[cards]]
text = "R2-D2"
first_revealed_installment = 1

[[cards]]
text = "Wicket"
first_revealed_installment = 3

[[cards]]
text = "Sith Jet Trooper"
first_revealed_installment = 11

[[cards]]
text = "Mustafar"
first_revealed_installment = 6

[[cards]]
text = "Knights of Ren"
first_revealed_installment = 7

[[cards]]
text = "The Millennium Falcon"
first_revealed_installment = 1

[[cards]]
text = "Tantive IV"
first_revealed_installment = 1

[[cards]]
text = "Nien Nunb"
first_revealed_installment = 3

[[cards]]
text = "Snap Wexley"
first_revealed_installment = 7

[[cards]]
text = "Lieutenant Connix"
first_revealed_installment = 7

[[cards]]
text = "Aftab Ackbar"
first_revealed_installment = 11

[[cards]]
text = "Commander D'Acy"
first_revealed_installment = 9

[[cards]]
text = "Han Solo"
first_revealed_installment = 1

[[cards]]
text = "Sith Acolytes"
first_revealed_installment = 11

[[cards]]
text = "X-wing"
first_revealed_installment = 1

[[cards]]
text = "Tatooine"
first_revealed_installment = 1

[[cards]]
text = "Lars Homestead"
first_revealed_installment = 1

[[cards]]
text = "Sith Language"
first_revealed_installment = 13

[[cards]]
text = "Spice Runner Medallion"
first_revealed_installment = 11

[[cards]]
text = "Snoke's Clones"
first_revealed_installment = 11

[[cards]]
text = "Supreme Leader Snoke"
first_revealed_installment = 7

[[cards]]
text = "Qui-Gon Jinn"
first_revealed_installment = 4

[[cards]]
text = "Obi-Wan Kenobi"
first_revealed_installment = 1

[[cards]]
text = "Anakin Skywalker"
first_revealed_installment = 4

[[cards]]
text = "Mace Windu"
first_revealed_installment = 4

[[cards]]
text = "Yoda"
first_revealed_installment = 2

[[cards]]
text = "Ahsoka Tano"
first_revealed_installment = 13

[[cards]]
text = "Kanan Jarrus"
first_revealed_installment = 13

[[cards]]
text = "Aayla Secura"
first_revealed_installment = 5

[[cards]]
text = "Luminara Unduli"
first_revealed_installment = 5

[[cards]]
text = "Adi Gallia"
first_revealed_installment = 4

[[cards]]
text = "Xyston-class Star Destroyer"
first_revealed_installment = 11

[[cards]]
text = "First Order"
first_revealed_installment = 7

[[cards]]
text = "The Resistance"
first_revealed_installment = 7

[[cards]]
text = "Desert Speeder Chase"
first_revealed_installment = 11

[[cards]]
text = "Medal of Bravery"
first_revealed_installment = 1

[[cards]]
text = "Jedi Training Course"
first_revealed_installment = 11

[[cards]]
text = "Jedi Sacred Texts"
first_revealed_installment = 9

[[cards]]
text = "Force Ghost"
first_revealed_installment = 2

[[cards]]
text = "Vader's Melted Helmet"
first_revealed_installment = 7

[[cards]]
text = "Sith Fleet"
first_revealed_installment = 11

[[cards]]
text = "Training Remote"
first_revealed_installment = 1

[[cards]]
text = "Ahch-To"
first_revealed_installment = 7

[[cards]]
text = "Ewoks"
first_revealed_installment = 3

[[cards]]
text = "Palpatine's Wayfinder"
first_revealed_installment = 11

[[cards]]
text = "Vader's Wayfinder"
first_revealed_installment = 11

[[cards]]
text = "Sovereign Protector"
first_revealed_installment = 11

[[cards]]
text = "Oma Tres"
first_revealed_installment = 11

[[cards]]
text = "Stormtrooper Defectors"
first_revealed_installment = 11

[[cards]]
text = "Twin Sunset"
first_revealed_installment = 1

[[cards]]
text = "Yellow Lightsaber"
first_revealed_installment = 11

[[cards]]
text = "Lightspeed Skipping"
first_revealed_installment = 11

[[cards]]
text = "Ur-Kittat"
first_revealed_installment = 11

[[cards]]
text = "Scavenger Staff"
first_revealed_installment = 7

[[cards]]
text = "Red Five"
first_revealed_installment = 1

[[cards]]
text = "Sith Arena"
first_revealed_installment = 11

[[cards]]
text = "Spice Runner"
first_revealed_installment = 11
